name: ci-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Setup Go version 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18
        id: go

      - name: Checkout the code of this respo into runner
        uses: actions/checkout@v3

      - name: Install go-migrate cli tool
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-arm64.tar.gz | tar xvz
          sudo mv migrate-linux-arm64.tar.gz /usr/bin/migrate

      - name: Run migrations
        run: up -path=/db/migration -database="postgres://root:secret@localhost:5432/simple_bank?sslmode=disable" -verbose

      - name: Run tests
        run: make test
